---
title: "Road Safety Dissertation"
author: "Kathlyn Ycong"
date: '2022-05-12'
output: word_document
---

# Abstract

Abstract should contain a brief summary of the aim, methodologies, finds and conclusions of the disseration. That abstract should normally be fewer than 350 words.

# Acknowledgement

# 1 Introduction

The purpose is to describe the general subject area, state the research problem of interest, outline the main results of the thesis, and put the results in context with wider subject area and its applications.

The main body of the text must be divided into a logical scheme which is followed consistently throughout the work. It usually starts with an introduction chapter and ends with a conclusion.


## 1.1 Motivation

we wanted to create an R Package so that we calcu

## 1.2 Problem Statement

- The research problem is clearly and concisely **defined** (e.g. as research questions).

- The research is clearly **motivated**, i.e. its importance is explained

- The **scope** of the research done in the project is clearly stated.

## 1.3 Research Objectives

Overall Aim/Goal of the Project
- MoT are looking to adapt trafficalmr
- Adding value to road safety policies that can help the lives of New Zealanders
- Better safety outcomes for active transport modes
- this project will set the data foundations for adapting trafficalmr to the New Zealand context and enable policy/traffic calming intervention analyses.
- The main part of the work will involve data processing. But the variety of the data will keep the work interesting - the work involves geospatial datasets (raw and derived), APIs (Cyclestreets, OpenStreetMap) and census datasets
- The policy analysis will use the developed data foundations to estimate the casualty rate per billion kilometres for walking and cycling to work commutes
- Data visualisation and data communication will be an ideal closing point for this project.

trafficalmr open source project (in R)
- an initiative from the UK that seeks to automate and analyse: risk exposure, traffic casualty and intervention indicators to better understand road safety outcomes in the UK.

## 1.4 Contributions

## 1.5 Overview of Approach

## 1.6 Scope & Structure
- The scope of the research is 

for commuters that are travelling from their usual residence to work


# 2 Related Work

- An appropriate number and range of related works is cited ( >= 20 for dissertation)

- Related work is appropriately organised (e.g. using subsections or tables)

- Important concepts and contributions of related work are explained

- Related work is discussed in relation to teh research problem and proposed solution

- Gaps in the knowledge about the research problem are identified to explain the novelty of the research in the report.

++++++++++++++++++++++++++++++++++++++++++++++++++++

Wanted to set the scene on the relevance of road safety, how New Zealand's road safety measure compared to other countries. 

## 2.1 Road Safety

## 2.2 Policies on Road Safety
- Currently Road Safety Policies in new zealand

## 2.3 Exposure

## 2.4 Risk
- compare why some methodologies are using time travelled vs distance travelled. Why are we using distance travelled in this project

## 2.5 Geocomputation/Spatial Analysis
- what is geocomputation or Spatial Data Analysis

## 2.6 Hotspot Analysis
- KDE
- Autocorrelation


## Summary

# 3 Methodology and Data Analysis

- The methodology used to address the research problem is clearly specified so that an independent research could replicate the results.

- All important concepts used in research are clearly explained

- Statements and claims are appropriately supported with results or evidence, e.g. by citing related work.

Assumptions and limitations of the research of the research are stated and their implications discussed.

The research outcomes are critically evaluated (reporting strengths and weaknesses)

## 3.1 Assumptions

- Assuming that start and end of the journey of a commuter using driving as a method for driving is the centroid of SA2

- Due to data sensitivity, stats NZ does not provide actual start and end coordinates of each travel

- We assumed that the router provides the best route from source to destination

## 3.2 Overview

## 3.3 Limitations

- The most recent latest journey to work data is 2018. Noting that due to COVID and changes over time, journey to work have changed.

## 3.4 Simulating Routes

## 3.5 Getting the Distance Travelled

## 3.6 Summary

# 4 Experimental Design


## 4.1 Implementation
- 

## 4.2 Validating Route Simulation
- Validating the the routes 


## 4.3 Datasets

### a. Journey to work data

### b. CAS data

### c. SA2 Polygons

### d. Auckland Traffic Counter

## 4.3 Libraries Used/Packages

### a. ghroute

### b. sf 

### c.autocorrelation

# 5 Results

## 5.1 Usual Residence Plot

## 5.2 Usual Work Plot

## 5.3 

# 6 Conclusion

The report draws convincing conclusions that are clearly related to the researcg problem and supported b teh research. 

The report points out relevant and interesting future work.

## 6.1 Achievement

## 6.2 Limitations

## 6.3 Future Directions

# References

# Appendix
